# Generated by Django 6.0.2 on 2026-03-25 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarkets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supermarket',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='supermarkets/'),
        ),
    ]
